# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
    ]
