# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Rating')),
            ],
        ),
    ]
