# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseclient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseclient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='baseclient',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
