# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_auto_20180306_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.BaseClient')),
                ('rates', models.TextField()),
            ],
            bases=('client.baseclient',),
        ),
    ]
