# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COUPE', 'Coupe'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('V_SERIES', 'V Series'), ('HYBRID', 'Hybrid')], max_length=15)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
            ],
        ),
    ]
